version: "3.5"

services:
  api01: &api
    hostname: api01
    container_name: api01
    image: jeanmolossi/rinha-backend-2024-q1:latest
    environment:
      DB_HOSTNAME: db
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "40MB"

  api02:
    <<: *api
    hostname: api02
    container_name: api02
    environment:
      DB_HOSTNAME: db
      PORT: 8080
    ports:
      - "8081:8080"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "250MB"
