SET client_encoding = 'UTF8';
SET client_min_messages = warning;

DROP TABLE IF EXISTS clientes;
DROP TABLE IF EXISTS transacoes;
DROP TABLE IF EXISTS saldos;

CREATE UNLOGGED TABLE IF NOT EXISTS clientes (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 10 START 1 CACHE 1 NO CYCLE ),
	nome VARCHAR(50) NOT NULL,
	limite INTEGER NOT NULL
);

CREATE UNLOGGED TABLE IF NOT EXISTS transacoes (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE ),
	cliente_id INTEGER NOT NULL,
	valor INTEGER NOT NULL,
	tipo CHAR(1) NOT NULL,
	descricao VARCHAR(10) NOT NULL,
	realizada_em TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT fk_clientes_transacoes_id
		FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE INDEX IF NOT EXISTS cliente_transacoes_idx ON transacoes (
	cliente_id DESC NULLS LAST
);

CREATE INDEX CONCURRENTLY realizada_idx ON transacoes (
	realizada_em DESC NULLS LAST
);

CREATE UNLOGGED TABLE saldos (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 10 START 1 CACHE 1 NO CYCLE ),
	cliente_id INTEGER NOT NULL,
	valor INTEGER NOT NULL,
	limite INTEGER NOT NULL,
	CONSTRAINT fk_clientes_saldos_id
		FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE INDEX IF NOT EXISTS cliente_saldos_idx ON saldos (
	cliente_id DESC NULLS LAST
);

CREATE TYPE SALDO_LIMITE AS (saldo_atual NUMERIC, limite INT);

CREATE OR REPLACE FUNCTION atualiza_saldo(cid INTEGER, val INTEGER, typ VARCHAR(1), descr VARCHAR(10))
RETURNS SALDO_LIMITE
AS $$
DECLARE
	saldo_limite SALDO_LIMITE;
BEGIN
	IF typ = 'c' THEN
		UPDATE "saldos" SET "valor" = ("valor" + val) WHERE "cliente_id" = cid
		RETURNING "valor", "limite" INTO SALDO_LIMITE;

		INSERT INTO transacoes ("cliente_id", "valor", "tipo", "descricao", "realizada_em")
		VALUES (cid, val, 'c', descr, now());
		RETURN saldo_limite;
	END IF;

	UPDATE "saldos" SET "valor" = "valor" - val WHERE "cliente_id" = cid
		AND "valor" - val >= "limite" * -1
	RETURNING "valor", "limite" INTO SALDO_LIMITE;

	IF saldo_limite IS NOT NULL THEN
		INSERT INTO transacoes ("cliente_id", "valor", "tipo", "descricao", "realizada_em")
		VALUES (cid, val, 'd', descr, now());
		RETURN saldo_limite;
	END IF;

	RAISE EXCEPTION 'Insufficient limit';
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
	INSERT INTO clientes (nome, limite)
	VALUES
		('o barato sai caro', 1000 * 100),
		('zan corp ltda', 800 * 100),
		('les cruders', 10000 * 100),
		('padaria joia de cocaia', 100000 * 100),
		('kid mais', 5000 * 100);

	INSERT INTO saldos (cliente_id, valor, limite)
		SELECT id, 0, limite FROM clientes;
END;
$$;